const fruits = [
  {
    name: "Persimmon",
    id: 52,
    family: "Ebenaceae",
    order: "Rosales",
    genus: "Diospyros",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Fuyu_persimmon_fruits%2C_one_cut_open.jpg/500px-Fuyu_persimmon_fruits%2C_one_cut_open.jpg",
    nutritions: {
      calories: 81,
      fat: 0,
      sugar: 18,
      carbohydrates: 18,
      protein: 0,
    },
  },
  {
    name: "Strawberry",
    id: 3,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Fragaria",
    img: "https://upload.wikimedia.org/wikipedia/commons/2/29/PerfectStrawberry.jpg",
    nutritions: {
      calories: 29,
      fat: 0.4,
      sugar: 5.4,
      carbohydrates: 5.5,
      protein: 0.8,
    },
  },
  {
    name: "Banana",
    id: 1,
    family: "Musaceae",
    order: "Zingiberales",
    genus: "Musa",
    img: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg",
    nutritions: {
      calories: 96,
      fat: 0.2,
      sugar: 17.2,
      carbohydrates: 22,
      protein: 1,
    },
  },
  {
    name: "Tomato",
    id: 5,
    family: "Solanaceae",
    order: "Solanales",
    genus: "Solanum",
    img: "https://upload.wikimedia.org/wikipedia/commons/8/88/Bright_red_tomato_and_cross_section02.jpg",
    nutritions: {
      calories: 74,
      fat: 0.2,
      sugar: 2.6,
      carbohydrates: 3.9,
      protein: 0.9,
    },
  },
  {
    name: "Pear",
    id: 4,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Pyrus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Pears.jpg/500px-Pears.jpg",
    nutritions: {
      calories: 57,
      fat: 0.1,
      sugar: 10,
      carbohydrates: 15,
      protein: 0.4,
    },
  },
  {
    name: "Durian",
    id: 60,
    family: "Malvaceae",
    order: "Malvales",
    genus: "Durio",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Durian_in_black.jpg/960px-Durian_in_black.jpg",
    nutritions: {
      calories: 147,
      fat: 5.3,
      sugar: 6.75,
      carbohydrates: 27.1,
      protein: 1.5,
    },
  },
  {
    name: "Blackberry",
    id: 64,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Rubus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Ripe%2C_ripening%2C_and_green_blackberries.jpg/500px-Ripe%2C_ripening%2C_and_green_blackberries.jpg",
    nutritions: {
      calories: 40,
      fat: 0.4,
      sugar: 4.5,
      carbohydrates: 9,
      protein: 1.3,
    },
  },
  {
    name: "Lingonberry",
    id: 65,
    family: "Ericaceae",
    order: "Ericales",
    genus: "Vaccinium",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Vaccinium_vitis-idaea_20060824_003.jpg/500px-Vaccinium_vitis-idaea_20060824_003.jpg",
    nutritions: {
      calories: 50,
      fat: 0.34,
      sugar: 5.74,
      carbohydrates: 11.3,
      protein: 0.75,
    },
  },
  {
    name: "Kiwi",
    id: 66,
    family: "Actinidiaceae",
    order: "Struthioniformes",
    genus: "Apteryx",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Hardy-Kiwi-Comparison-3.jpg/500px-Hardy-Kiwi-Comparison-3.jpg",
    nutritions: {
      calories: 61,
      fat: 0.5,
      sugar: 9,
      carbohydrates: 15,
      protein: 1.1,
    },
  },
  {
    name: "Lychee",
    id: 67,
    family: "Sapindaceae",
    order: "Sapindales",
    genus: "Litchi",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Litchi_chinensis_fruits.JPG/500px-Litchi_chinensis_fruits.JPG",
    nutritions: {
      calories: 66,
      fat: 0.44,
      sugar: 15,
      carbohydrates: 17,
      protein: 0.8,
    },
  },
  {
    name: "Pineapple",
    id: 10,
    family: "Bromeliaceae",
    order: "Poales",
    genus: "Ananas",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Pineapple_%27Victoria%27_with_slice.jpg/500px-Pineapple_%27Victoria%27_with_slice.jpg",
    nutritions: {
      calories: 50,
      fat: 0.12,
      sugar: 9.85,
      carbohydrates: 13.12,
      protein: 0.54,
    },
  },
  {
    name: "Fig",
    id: 68,
    family: "Moraceae",
    order: "Rosales",
    genus: "Ficus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Fig_%28Ficus_carica%29_fruits.jpg/500px-Fig_%28Ficus_carica%29_fruits.jpg",
    nutritions: {
      calories: 74,
      fat: 0.3,
      sugar: 16,
      carbohydrates: 19,
      protein: 0.8,
    },
  },
  {
    name: "Gooseberry",
    id: 69,
    family: "Grossulariaceae",
    order: "Saxifragales",
    genus: "Ribes",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Stachelbeeren.jpg/330px-Stachelbeeren.jpg",
    nutritions: {
      calories: 44,
      fat: 0.6,
      sugar: 0,
      carbohydrates: 10,
      protein: 0.9,
    },
  },
  {
    name: "Passionfruit",
    id: 70,
    family: "Passifloraceae",
    order: "Malpighiales",
    genus: "Passiflora",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Passion_fruits_-_whole_and_halved.jpg/500px-Passion_fruits_-_whole_and_halved.jpg",
    nutritions: {
      calories: 97,
      fat: 0.7,
      sugar: 11.2,
      carbohydrates: 22.4,
      protein: 2.2,
    },
  },
  {
    name: "Plum",
    id: 71,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Cherry_plums.jpg/500px-Cherry_plums.jpg",
    nutritions: {
      calories: 46,
      fat: 0.28,
      sugar: 9.92,
      carbohydrates: 11.4,
      protein: 0.7,
    },
  },
  {
    name: "Orange",
    id: 2,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/960px-Oranges_-_whole-halved-segment.jpg",
    nutritions: {
      calories: 43,
      fat: 0.2,
      sugar: 8.2,
      carbohydrates: 8.3,
      protein: 1,
    },
  },
  {
    name: "GreenApple",
    id: 72,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Malus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Granny_smith_and_cross_section.jpg/500px-Granny_smith_and_cross_section.jpg",
    nutritions: {
      calories: 21,
      fat: 0.1,
      sugar: 6.4,
      carbohydrates: 3.1,
      protein: 0.4,
    },
  },
  {
    name: "Raspberry",
    id: 23,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Rubus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Fert%C5%91di_k%C3%A1rmin_m%C3%A1lna.JPG/500px-Fert%C5%91di_k%C3%A1rmin_m%C3%A1lna.JPG",
    nutritions: {
      calories: 53,
      fat: 0.7,
      sugar: 4.4,
      carbohydrates: 12,
      protein: 1.2,
    },
  },
  {
    name: "Watermelon",
    id: 25,
    family: "Cucurbitaceae",
    order: "Cucurbitales",
    genus: "Citrullus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Watermelon_cross_BNC.jpg/500px-Watermelon_cross_BNC.jpg",
    nutritions: {
      calories: 30,
      fat: 0.2,
      sugar: 6,
      carbohydrates: 8,
      protein: 0.6,
    },
  },
  {
    name: "Lemon",
    id: 26,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/P1030323.JPG/500px-P1030323.JPG",
    nutritions: {
      calories: 29,
      fat: 0.3,
      sugar: 2.5,
      carbohydrates: 9,
      protein: 1.1,
    },
  },
  {
    name: "Mango",
    id: 27,
    family: "Anacardiaceae",
    order: "Sapindales",
    genus: "Mangifera",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Mangos_-_single_and_halved.jpg/960px-Mangos_-_single_and_halved.jpg",
    nutritions: {
      calories: 60,
      fat: 0.38,
      sugar: 13.7,
      carbohydrates: 15,
      protein: 0.82,
    },
  },
  {
    name: "Blueberry",
    id: 33,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Fragaria",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Blueberries.jpg/500px-Blueberries.jpg",
    nutritions: {
      calories: 29,
      fat: 0.4,
      sugar: 5.4,
      carbohydrates: 5.5,
      protein: 0,
    },
  },
  {
    name: "Apple",
    id: 6,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Malus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pink_lady_and_cross_section.jpg/500px-Pink_lady_and_cross_section.jpg",
    nutritions: {
      calories: 52,
      fat: 0.4,
      sugar: 10.3,
      carbohydrates: 11.4,
      protein: 0.3,
    },
  },
  {
    name: "Guava",
    id: 37,
    family: "Myrtaceae",
    order: "Myrtales",
    genus: "Psidium",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Guava_ID.jpg/500px-Guava_ID.jpg",
    nutritions: {
      calories: 68,
      fat: 1,
      sugar: 9,
      carbohydrates: 14,
      protein: 2.6,
    },
  },
  {
    name: "Apricot",
    id: 35,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Apricot_and_cross_section.jpg/500px-Apricot_and_cross_section.jpg",
    nutritions: {
      calories: 15,
      fat: 0.1,
      sugar: 3.2,
      carbohydrates: 3.9,
      protein: 0.5,
    },
  },
  {
    name: "Melon",
    id: 41,
    family: "Cucurbitaceae",
    order: "Cucurbitaceae",
    genus: "Cucumis",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Cantaloupe_and_canary_melon.jpg/960px-Cantaloupe_and_canary_melon.jpg",
    nutritions: {
      calories: 34,
      fat: 0,
      sugar: 8,
      carbohydrates: 8,
      protein: 0,
    },
  },
  {
    name: "Tangerine",
    id: 77,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/TangerineFruit.jpg/500px-TangerineFruit.jpg",
    nutritions: {
      calories: 45,
      fat: 0.4,
      sugar: 9.1,
      carbohydrates: 8.3,
      protein: 0,
    },
  },
  {
    name: "Pitaya",
    id: 78,
    family: "Cactaceae",
    order: "Caryophyllales",
    genus: "Cactaceae",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Pitaya_cross_section_ed2.jpg/500px-Pitaya_cross_section_ed2.jpg",
    nutritions: {
      calories: 36,
      fat: 0.4,
      sugar: 3,
      carbohydrates: 7,
      protein: 1,
    },
  },
  {
    name: "Lime",
    id: 44,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Citrus_hystrix_dsc07772.jpg/500px-Citrus_hystrix_dsc07772.jpg",
    nutritions: {
      calories: 25,
      fat: 0.1,
      sugar: 1.7,
      carbohydrates: 8.4,
      protein: 0.3,
    },
  },
  {
    name: "Pomegranate",
    id: 79,
    family: "Lythraceae",
    order: "Myrtales",
    genus: "Punica",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Pomegranate_fruit_-_whole_and_piece_with_arils.jpg/500px-Pomegranate_fruit_-_whole_and_piece_with_arils.jpg",
    nutritions: {
      calories: 83,
      fat: 1.2,
      sugar: 13.7,
      carbohydrates: 18.7,
      protein: 1.7,
    },
  },
  {
    name: "Dragonfruit",
    id: 80,
    family: "Cactaceae",
    order: "Caryophyllales",
    genus: "Selenicereus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Pitaya_Colors.jpg/250px-Pitaya_Colors.jpg",
    nutritions: {
      calories: 60,
      fat: 1.5,
      sugar: 8,
      carbohydrates: 9,
      protein: 9,
    },
  },
  {
    name: "Grape",
    id: 81,
    family: "Vitaceae",
    order: "Vitales",
    genus: "Vitis",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Grapes%2C_Rostov-on-Don%2C_Russia.jpg/500px-Grapes%2C_Rostov-on-Don%2C_Russia.jpg",
    nutritions: {
      calories: 69,
      fat: 0.16,
      sugar: 16,
      carbohydrates: 18.1,
      protein: 0.72,
    },
  },
  {
    name: "Morus",
    id: 82,
    family: "Moraceae",
    order: "Rosales",
    genus: "Morus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Morus_alba_FrJPG.jpg/500px-Morus_alba_FrJPG.jpg",
    nutritions: {
      calories: 43,
      fat: 0.39,
      sugar: 8.1,
      carbohydrates: 9.8,
      protein: 1.44,
    },
  },
  {
    name: "Feijoa",
    id: 76,
    family: "Myrtaceae",
    order: "Myrtoideae",
    genus: "Sellowiana",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Acca_sellowiana_Fruit_MHNT_Fronton.jpg/500px-Acca_sellowiana_Fruit_MHNT_Fronton.jpg",
    nutritions: {
      calories: 44,
      fat: 0.4,
      sugar: 3,
      carbohydrates: 8,
      protein: 0.6,
    },
  },
  {
    name: "Avocado",
    id: 84,
    family: "Lauraceae",
    order: "Laurales",
    genus: "Persea",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Avocado_Hass_-_single_and_halved.jpg/500px-Avocado_Hass_-_single_and_halved.jpg",
    nutritions: {
      calories: 160,
      fat: 14.66,
      sugar: 0.66,
      carbohydrates: 8.53,
      protein: 2,
    },
  },
  {
    name: "Kiwifruit",
    id: 85,
    family: "Actinidiaceae",
    order: "Ericales",
    genus: "Actinidia",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Hardy-Kiwi-Comparison-3.jpg/500px-Hardy-Kiwi-Comparison-3.jpg",
    nutritions: {
      calories: 61,
      fat: 0.5,
      sugar: 8.9,
      carbohydrates: 14.6,
      protein: 1.14,
    },
  },
  {
    name: "Cranberry",
    id: 87,
    family: "Ericaceae",
    order: "Ericales",
    genus: "Vaccinium",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Cranberries20101210.jpg/500px-Cranberries20101210.jpg",
    nutritions: {
      calories: 46,
      fat: 0.1,
      sugar: 4,
      carbohydrates: 12.2,
      protein: 0.4,
    },
  },
  {
    name: "Cherry",
    id: 9,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Cherry_season_%2848216568227%29.jpg/500px-Cherry_season_%2848216568227%29.jpg",
    nutritions: {
      calories: 50,
      fat: 0.3,
      sugar: 8,
      carbohydrates: 12,
      protein: 1,
    },
  },
  {
    name: "Peach",
    id: 86,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Autumn_Red_peaches.jpg/500px-Autumn_Red_peaches.jpg",
    nutritions: {
      calories: 39,
      fat: 0.25,
      sugar: 8.4,
      carbohydrates: 9.5,
      protein: 0.9,
    },
  },
  {
    name: "Jackfruit",
    id: 94,
    family: "Moraceae",
    order: "Rosales",
    genus: "Artocarpus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Jackfruit_hanging.JPG/500px-Jackfruit_hanging.JPG",
    nutritions: {
      calories: 95,
      fat: 0,
      sugar: 19.1,
      carbohydrates: 23.2,
      protein: 1.72,
    },
  },
  {
    name: "Horned Melon",
    id: 95,
    family: "Cucurbitaceae",
    order: "Cucurbitales",
    genus: "Cucumis",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Cucumis_metuliferus_fruit_-_whole_and_cross_section.jpg/500px-Cucumis_metuliferus_fruit_-_whole_and_cross_section.jpg",
    nutritions: {
      calories: 44,
      fat: 1.26,
      sugar: 0.5,
      carbohydrates: 7.56,
      protein: 1.78,
    },
  },
  {
    name: "Hazelnut",
    id: 96,
    family: "Betulaceae",
    order: "Fagales",
    genus: "Corylus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Hazelnuts_%28Corylus_avellana%29_-_whole_with_kernels.jpg/500px-Hazelnuts_%28Corylus_avellana%29_-_whole_with_kernels.jpg",
    nutritions: {
      calories: 628,
      fat: 61,
      sugar: 4.3,
      carbohydrates: 17,
      protein: 15,
    },
  },
  {
    name: "Pomelo",
    id: 98,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Pomelo_fruit.jpg/500px-Pomelo_fruit.jpg",
    nutritions: {
      calories: 37,
      fat: 0,
      sugar: 8.5,
      carbohydrates: 9.67,
      protein: 0.82,
    },
  },
  {
    name: "Mangosteen",
    id: 99,
    family: "Clusiaceae",
    order: "Malpighiales",
    genus: "Garcinia",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Mangosteens_-_whole_and_opened.jpg/500px-Mangosteens_-_whole_and_opened.jpg",
    nutritions: {
      calories: 73,
      fat: 0.58,
      sugar: 16.11,
      carbohydrates: 17.91,
      protein: 0.41,
    },
  },
  {
    name: "Pumpkin",
    id: 100,
    family: "Cucurbitaceae",
    order: "Cucurbitales",
    genus: "Cucurbita",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/FrenchMarketPumpkinsB.jpg/960px-FrenchMarketPumpkinsB.jpg",
    nutritions: {
      calories: 25,
      fat: 0.3,
      sugar: 3.3,
      carbohydrates: 4.6,
      protein: 1.1,
    },
  },
  {
    name: "Japanese Persimmon",
    id: 101,
    family: " Ebenaceae",
    order: " Ericales",
    genus: "Diospyros",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Persimmon_%28fuyu%29.jpg/500px-Persimmon_%28fuyu%29.jpg",
    nutritions: {
      calories: 70,
      fat: 0.2,
      sugar: 13,
      carbohydrates: 19,
      protein: 0.6,
    },
  },
  {
    name: "Papaya",
    id: 42,
    family: "Caricaceae",
    order: "Brassicales",
    genus: "Carica",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Papaya_-_longitudinal_section.jpg/960px-Papaya_-_longitudinal_section.jpg",
    nutritions: {
      calories: 39,
      fat: 0.3,
      sugar: 4.4,
      carbohydrates: 5.8,
      protein: 0.5,
    },
  },
  {
    name: "Annona",
    id: 103,
    family: "Annonaceae",
    order: "Rosales",
    genus: "Annonas",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Sugar_apple_with_cross_section.jpg/500px-Sugar_apple_with_cross_section.jpg",
    nutritions: {
      calories: 92,
      fat: 0.29,
      sugar: 3.4,
      carbohydrates: 19.1,
      protein: 1.5,
    },
  },
  {
    name: "Ceylon Gooseberry",
    id: 104,
    family: "Salicaceae",
    order: "Malpighiales",
    genus: "Dovyalis",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Stachelbeere_%28Ribes_uva-crispa%29.jpg/330px-Stachelbeere_%28Ribes_uva-crispa%29.jpg",
    nutritions: {
      calories: 47,
      fat: 0.3,
      sugar: 8.1,
      carbohydrates: 9.6,
      protein: 1.2,
    },
  },
];

export default fruits;
